In [77]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('evaluare.csv')

In [3]:
df2 = pd.read_csv('12-07_orig.csv')

In [4]:
df2.head()

,Nume,Poziția în ierarhie pe județ,Poziția în ierarhie pe țară,Unitatea de învățământ,Județul,Promotie anterioară,Forma învățământ,Specializare,Limba și literatura română Competențe,Limba și literatura română Scris,...,Disciplina obligatorie a profilului Nota,Disciplina obligatorie a profilului Contestație,Disciplina obligatorie a profilului Nota finală,Disciplina la alegere,Disciplina la alegere Nota,Disciplina la alegere Contestație,Disciplina la alegere Nota finală,Competențe digitale,Media,Rezultatul final
0,A. Anei G. Ana Maria,1111,37997,"Colegiul National ""Stefan Cel Mare"" Tirgu Neamt",NT,Nu,Zi,Matematica-Informatica,Experimentat,8.85,...,5.60,NaN,5.60,"Anatomie si fiziologie umana, genetica si ecol...",8.85,NaN,8.85,Avansat,7.77,Reușit
1,A-Anei I. Flaviu-Octavian,1062,40643,"Liceul De Arte Plastice ""Hans Mattis-Teutsch"" ...",BV,Nu,Zi,"Arhitectura, arte ambientale si design",Avansat,6.30,...,7.15,NaN,7.15,Geografie,9.50,NaN,9.50,Experimentat,7.65,Reușit
2,Aanegroae S. C. Ana-Maria,57,2206,"Colegiul National ""Petru Rares"" Piatra Neamt",NT,Nu,Zi,Matematica-Informatica,Experimentat,8.40,...,9.70,NaN,9.70,Fizica,9.55,NaN,9.55,Experimentat,9.60,Reușit
3,Aanei G. Alexandru,754,24312,"Colegiul National ""Ferdinand I"" Bacau",BC,Nu,Zi,Matematica-Informatica,Experimentat,8.60,...,8.00,NaN,8.00,Informatica T1 C/C++,8.50,NaN,8.50,Experimentat,8.37,Reușit
4,Aanei I. Ana Maria,2626,93520,"Colegiul Tehnic ""Gheorghe Cartianu"" Piatra Neamt",NT,Nu,Zi,Tehnician desenator pentru constructii si inst...,Experimentat,5.60,...,3.20,3.15,3.20,Biologie vegetala si animala T1,7.70,NaN,7.70,Experimentat,5.50,Respins

In [5]:
df.head()

,Unnamed: 0,Nume,Unnamed: 2,SCOALA,Media la admitere,Media teze nationale,Media de absolvire,Nota la limba romana,Nota la matematica,OPTIONAL8,OPTIONAL8 NOTA,Limba materna8,Limba materna8 nota
0,NaN,SZABO E. CSILLA REKA,CLUJ,SCOALA CU CLASELE I-VIII NR. 1 DEJ,9.87,9.75,10.00,9.67,9.35,Geografie,10.0,Maghiara,10
1,NaN,KEGYES I. KRISZTINA TIMEA,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.69,9.45,9.93,8.97,9.95,Istorie,9.8,Maghiara,9.07
2,NaN,FULOP BALOGH A. BEATRIX EMOKE,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.66,9.35,9.97,8.42,9.90,Istorie,9.5,Maghiara,9.57
3,NaN,DEAK I. NORBERT,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.60,9.24,9.97,7.85,10.00,Istorie,10.0,Maghiara,9.12
4,NaN,BALOGH E. IMOLA RENATA,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.53,9.45,9.62,8.87,9.57,Istorie,9.8,Maghiara,9.55

In [6]:
df.shape

(585, 13)

In [7]:
df.Nume

0                      SZABO E. CSILLA REKA
1                 KEGYES I. KRISZTINA TIMEA
2             FULOP BALOGH A. BEATRIX EMOKE
3                           DEAK I. NORBERT
4                    BALOGH E. IMOLA RENATA
5                      KIS A. ESZTER CSILLA
6                           KOVACS P. KINGA
7                  TOTH L. NORBERT SZABOLCS
8                           KISPAL Z. TIMEA
9                           BALAZS T. TIMEA
10                   MATHE A. SANDOR GYORGY
11                     VRANNAI S. BERNADETT
12                     DEBRECZENI I. ISTVAN
13                           IOASCO M. KATI
14                        BARABAS A. ESZTER
15                      PAPP ZAKOR A. JANKA
16                KEDVES J. BRIGITTA-RENATA
17                            MAAK P. GABOR
18                     KISS S. RENATA JULIA
19                          PUSCAS S. DAVID
20                      BIRO E. AGNES TUNDE
21                   SZAPPAN I. ALPAR JANOS
22                 REIDER L. SZILARD ROBERT
23                    KUTAS I. BERNAT TAMAS
24                  VLADAR A. ANTAL FERENCZ
25                   PETERFI C. WANDA EMESE
26                  BOZSA I. ANDREA SIDONIA
27                       FEKETE C. DOROTTYA
28                     KAPTALAN E. SZABOLCS
29                         ENYEDI Z. ROBERT
                       ...
555                    BORZA M. IOANA MARIA
556               SCHIOP E. EMILIA NICOLETA
557                         AGRATINI O. ADA
558                 CRISAN A. RADU-CRISTIAN
559                 OLAR D. TEODORA - MARIA
560                     TROFIN I. VLAD-IOAN
561               BOAR D. PATRICIA -DANIELA
562                IRIMESCU A. OANA-FLORINA
563                            DAN P. PAULA
564                SANDRU C. DENISA CAMELIA
565                 RAU I. ALEXANDRU-MARCEL
566                 MOCAN I. MARIA MADALINA
567               NISTOR M. ANDREEA CLAUDIA
568               MOLDOVAN R. GEORGIA MARIA
569               OPREA V. ADRIANA-GABRIELA
570                  MISCA P. MARIA MIHAELA
571                    OPREA O. ANDRA ALINA
572                 BLEZA N. ELENA BEATRICE
573    MARINCEAN A. DANIELA-AUGUSTA-MIHAELA
574                        MURESAN M. DIANA
575                      FAZAKAS S. CLAUDIA
576                        CERNEA I. IRIMIE
577               PRESECAN L. IULIA ADELINA
578                       PINTILIE C. LAURA
579                   NICA D. IULIA MARCELA
580            ARUNCUTEAN D. DOMNITA-STANCA
581                   FAGADAR S. PAUL-SORIN
582                    PACURAR A. ALEXANDRU
583                MOCA F. FELICIA - GIULIA
584                   RUNCAN I. ADINA IOANA
Name: Nume, Length: 585, dtype: object

In [8]:
df.Nume = df.Nume.str.lower()
df2.Nume = df2.Nume.str.lower()

In [9]:
df.Nume = df.Nume.str.strip()
df2.Nume = df2.Nume.str.strip()

In [10]:
df.head()

,Unnamed: 0,Nume,Unnamed: 2,SCOALA,Media la admitere,Media teze nationale,Media de absolvire,Nota la limba romana,Nota la matematica,OPTIONAL8,OPTIONAL8 NOTA,Limba materna8,Limba materna8 nota
0,NaN,szabo e. csilla reka,CLUJ,SCOALA CU CLASELE I-VIII NR. 1 DEJ,9.87,9.75,10.00,9.67,9.35,Geografie,10.0,Maghiara,10
1,NaN,kegyes i. krisztina timea,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.69,9.45,9.93,8.97,9.95,Istorie,9.8,Maghiara,9.07
2,NaN,fulop balogh a. beatrix emoke,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.66,9.35,9.97,8.42,9.90,Istorie,9.5,Maghiara,9.57
3,NaN,deak i. norbert,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.60,9.24,9.97,7.85,10.00,Istorie,10.0,Maghiara,9.12
4,NaN,balogh e. imola renata,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.53,9.45,9.62,8.87,9.57,Istorie,9.8,Maghiara,9.55

In [11]:
s1 = pd.merge(df, df2, how='inner', on=['Nume'])

In [12]:
s1.head()

,Unnamed: 0,Nume,Unnamed: 2,SCOALA,Media la admitere,Media teze nationale,Media de absolvire,Nota la limba romana,Nota la matematica,OPTIONAL8,...,Disciplina obligatorie a profilului Nota,Disciplina obligatorie a profilului Contestație,Disciplina obligatorie a profilului Nota finală,Disciplina la alegere,Disciplina la alegere Nota,Disciplina la alegere Contestație,Disciplina la alegere Nota finală,Competențe digitale,Media,Rezultatul final
0,NaN,deak i. norbert,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.60,9.24,9.97,7.85,10.00,Istorie,...,10.00,NaN,10.00,Informatica T1 Pascal,9.85,NaN,9.85,Experimentat,9.03,Reușit
1,NaN,kovacs p. kinga,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.45,9.21,9.69,7.90,9.55,Istorie,...,9.30,NaN,9.30,"Anatomie si fiziologie umana, genetica si ecol...",10.00,NaN,10.00,Experimentat,8.96,Reușit
2,NaN,kovacs p. kinga,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.45,9.21,9.69,7.90,9.55,Istorie,...,8.85,NaN,8.85,Geografie,8.35,NaN,8.35,Mediu,8.56,Reușit
3,NaN,kispal z. timea,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.34,8.98,9.70,8.35,9.57,Istorie,...,9.15,NaN,9.15,Informatica T1 Pascal,9.50,NaN,9.50,Experimentat,9.10,Reușit
4,NaN,debreczeni i. istvan,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.07,8.56,9.58,7.37,8.95,Geografie,...,6.95,NaN,6.95,Chimie anorganica T2 Nivel I,9.00,NaN,9.00,Avansat,8.51,Reușit

In [13]:
df['Nume'].where(df['Nume'] == 'DEBRECZENI I. ISTVAN')

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
10     NaN
11     NaN
12     NaN
13     NaN
14     NaN
15     NaN
16     NaN
17     NaN
18     NaN
19     NaN
20     NaN
21     NaN
22     NaN
23     NaN
24     NaN
25     NaN
26     NaN
27     NaN
28     NaN
29     NaN
      ...
555    NaN
556    NaN
557    NaN
558    NaN
559    NaN
560    NaN
561    NaN
562    NaN
563    NaN
564    NaN
565    NaN
566    NaN
567    NaN
568    NaN
569    NaN
570    NaN
571    NaN
572    NaN
573    NaN
574    NaN
575    NaN
576    NaN
577    NaN
578    NaN
579    NaN
580    NaN
581    NaN
582    NaN
583    NaN
584    NaN
Name: Nume, Length: 585, dtype: object

In [14]:
df2[df2['Nume'].str.match('BOSCA')]

Empty DataFrame
Columns: [Nume, Poziția în ierarhie pe județ, Poziția în ierarhie pe țară, Unitatea de învățământ, Județul, Promotie anterioară, Forma învățământ, Specializare, Limba și literatura română
Competențe, Limba și literatura română
Scris, Limba și literatura română
Contestație, Limba și literatura română
Nota finală, Limba și literatura maternă, Limba și literatura maternă
Competențe, Limba și literatura maternă
Scris, Limba și literatura maternă
Contestație, Limba și literatura maternă
Nota finală, Limba modernă studiată, Limba modernă studiată
Nota, Disciplina obligatorie a profilului, Disciplina obligatorie a profilului
Nota, Disciplina obligatorie a profilului
Contestație, Disciplina obligatorie a profilului
Nota finală, Disciplina la alegere, Disciplina la alegere
Nota, Disciplina la alegere
Contestație, Disciplina la alegere
Nota finală, Competențe digitale, Media, Rezultatul final]
Index: []

[0 rows x 30 columns]

In [15]:
s1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 186 entries, 0 to 185
Data columns (total 42 columns):
Unnamed: 0                                          179 non-null float64
Nume                                                186 non-null object
Unnamed: 2                                          186 non-null object
SCOALA                                              186 non-null object
Media
la admitere                                   186 non-null float64
Media
teze nationale                                186 non-null float64
Media de
absolvire                                  186 non-null float64

Nota la
limba romana                               186 non-null float64
Nota la
matematica                                  186 non-null float64
OPTIONAL8                                           186 non-null object
OPTIONAL8 NOTA                                      186 non-null float64
Limba materna8                                      186 non-null object
Limba materna8 nota                                 186 non-null object
Poziția în ierarhie pe județ                        186 non-null int64
Poziția în ierarhie pe țară                         186 non-null int64
Unitatea de învățământ                              186 non-null object
Județul                                             186 non-null object
Promotie anterioară                                 186 non-null object
Forma învățământ                                    186 non-null object
Specializare                                        186 non-null object
Limba și literatura română
Competențe              185 non-null object
Limba și literatura română
Scris                   186 non-null float64
Limba și literatura română
Contestație             39 non-null float64
Limba și literatura română
Nota finală             186 non-null float64
Limba și literatura maternă                         17 non-null object
Limba și literatura maternă
Competențe             17 non-null object
Limba și literatura maternă
Scris                  17 non-null float64
Limba și literatura maternă
Contestație            3 non-null float64
Limba și literatura maternă
Nota finală            17 non-null float64
Limba modernă studiată                              186 non-null object
Limba modernă studiată
Nota                        134 non-null object
Disciplina obligatorie a profilului                 186 non-null object
Disciplina obligatorie a profilului
Nota           186 non-null float64
Disciplina obligatorie a profilului
Contestație    18 non-null float64
Disciplina obligatorie a profilului
Nota finală    186 non-null float64
Disciplina la alegere                               186 non-null object
Disciplina la alegere
Nota                         186 non-null float64
Disciplina la alegere
Contestație                  23 non-null float64
Disciplina la alegere
Nota finală                  186 non-null float64
Competențe digitale                                 185 non-null object
Media                                               186 non-null float64
Rezultatul final                                    186 non-null object
dtypes: float64(20), int64(2), object(20)
memory usage: 48.0+ KB

In [16]:
s1

,Unnamed: 0,Nume,Unnamed: 2,SCOALA,Media la admitere,Media teze nationale,Media de absolvire,Nota la limba romana,Nota la matematica,OPTIONAL8,...,Disciplina obligatorie a profilului Nota,Disciplina obligatorie a profilului Contestație,Disciplina obligatorie a profilului Nota finală,Disciplina la alegere,Disciplina la alegere Nota,Disciplina la alegere Contestație,Disciplina la alegere Nota finală,Competențe digitale,Media,Rezultatul final
0,NaN,deak i. norbert,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.60,9.24,9.97,7.85,10.00,Istorie,...,10.00,NaN,10.00,Informatica T1 Pascal,9.85,NaN,9.85,Experimentat,9.03,Reușit
1,NaN,kovacs p. kinga,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.45,9.21,9.69,7.90,9.55,Istorie,...,9.30,NaN,9.30,"Anatomie si fiziologie umana, genetica si ecol...",10.00,NaN,10.00,Experimentat,8.96,Reușit
2,NaN,kovacs p. kinga,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.45,9.21,9.69,7.90,9.55,Istorie,...,8.85,NaN,8.85,Geografie,8.35,NaN,8.35,Mediu,8.56,Reușit
3,NaN,kispal z. timea,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.34,8.98,9.70,8.35,9.57,Istorie,...,9.15,NaN,9.15,Informatica T1 Pascal,9.50,NaN,9.50,Experimentat,9.10,Reușit
4,NaN,debreczeni i. istvan,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",9.07,8.56,9.58,7.37,8.95,Geografie,...,6.95,NaN,6.95,Chimie anorganica T2 Nivel I,9.00,NaN,9.00,Avansat,8.51,Reușit
5,NaN,kaptalan e. szabolcs,CLUJ,"LICEUL TEORETIC ""BATHORY ISTVAN"" CLUJ-NAPOCA",8.53,7.78,9.29,6.17,8.70,Istorie,...,8.95,NaN,8.95,Informatica T1 Pascal,6.35,NaN,6.35,Avansat,7.55,Reușit
6,NaN,enyedi z. robert,CLUJ,"SCOALA CU CLASELE I-VIII ""BORBELY JOZSEF"" SAVA...",8.48,7.50,9.46,5.00,8.45,Geografie,...,5.65,NaN,5.65,Informatica T1 Pascal,5.85,5.6,5.85,Experimentat,5.93,Respins
7,1.0,mihon m. andreea,CLUJ,"SCOALA CU CLASELE I-VIII ""AVRAM IANCU"" TURDA",8.06,7.20,8.93,6.70,7.70,Geografie,...,7.50,NaN,7.50,Biologie vegetala si animala T1,8.65,NaN,8.65,Experimentat,7.83,Reușit
8,4.0,fodor i. robert,CLUJ,"SCOALA CU CLASELE I-VIII ""TEODOR MURASANU"" TURDA",7.74,6.86,8.63,6.92,6.25,Geografie,...,5.20,NaN,5.20,Biologie vegetala si animala T1,4.30,NaN,4.30,Mediu,4.83,Respins
9,8.0,groza m. bogdan-adrian,CLUJ,"SCOALA CU CLASELE I-VIII ""ANDREI SAGUNA"" TURDA",7.18,6.08,8.29,4.65,5.45,Geografie,...,3.20,3.00,3.20,Biologie vegetala si animala T1,3.35,NaN,3.35,Mediu,3.38,Respins
10,10.0,tatar m. daniela,CLUJ,"LICEUL TEORETIC ""PAVEL DAN"" CAMPIA TURZII",7.10,5.45,8.76,4.92,4.87,Geografie,...,2.30,2.15,2.30,Biologie vegetala si animala T1,9.00,NaN,9.00,Experimentat,5.70,Respins
11,14.0,felecan a. paul alexandru,CLUJ,"SCOALA CU CLASELE I-VIII ""SIMION BALINT"" COPACENI",6.99,6.15,7.83,5.72,6.20,Geografie,...,2.30,NaN,2.30,Fizica,4.20,3.5,3.50,Avansat,3.63,Respins
12,18.0,bulat p. elena,CLUJ,"SCOALA CU CLASELE I-VIII ""HOREA CLOSCA SI CRIS...",6.94,5.77,8.11,3.65,5.17,Geografie,...,1.90,NaN,1.90,Biologie vegetala si animala T1,3.95,NaN,3.95,Mediu,3.62,Respins
13,2.0,iancu i. andreea-diana,CLUJ,SCOALA CU CLASELE I-VIII SOPORU DE CAMPIE COM....,8.81,7.91,9.71,7.85,6.85,Geografie,...,8.40,NaN,8.40,Geografie,8.90,NaN,8.90,Mediu,8.77,Reușit
14,5.0,trif i. radu-mihai,CLUJ,SCOALA CU CLASELE I-VIII SOPORU DE CAMPIE COM....,8.37,7.30,9.45,7.00,6.95,Istorie,...,5.70,NaN,5.70,Geografie,7.80,NaN,7.80,Avansat,5.90,Respins
15,6.0,tandea d. andreea-simona,CLUJ,"SCOALA CU CLASELE I-VIII ""ANDREI SAGUNA"" TURDA",7.88,6.64,9.12,5.32,7.27,Geografie,...,5.00,NaN,5.00,Geografie,6.45,NaN,6.45,Experimentat,5.12,Respins
16,10.0,luca g. claudia,CLUJ,"SCOALA CU CLASELE I-VIII ""TEODOR MURASANU"" TURDA",7.60,6.82,8.38,6.35,5.52,Geografie,...,6.45,NaN,6.45,Geografie,5.60,NaN,5.60,Avansat,5.68,Respins
17,11.0,costantea i. marius-adrian,CLUJ,SCOALA CU CLASELE I-VIII SOPORU DE CAMPIE COM....,7.51,5.99,9.03,4.75,5.72,Istorie,...,5.00,NaN,5.00,Geografie,8.35,NaN,8.35,Mediu,6.12,Reușit
18,25.0,korondi p. cristian,CLUJ,SCOALA CU CLASELE I-VIII MOLDOVENESTI,7.04,6.22,7.87,5.72,5.80,Istorie,...,0.00,NaN,0.00,"Anatomie si fiziologie umana, genetica si ecol...",0.00,NaN,0.00,NaN,0.00,Respins
19,26.0,savan t. teodor dan,CLUJ,"SCOALA CU CLASELE I-VIII ""POTAISSA"" TURDA",7.03,6.51,7.55,6.15,5.00,Geografie,...,2.70,NaN,2.70,Biologie vegetala si animala T1,2.80,NaN,2.80,Avansat,3.50,Respins
20,27.0,muresan o. razvan,CLUJ,SCOALA CU CLASELE I-VIII CALARASI,7.03,6.13,7.94,4.47,5.37,Geografie,...,4.10,NaN,4.10,Geografie,5.20,NaN,5.20,Mediu,4.47,Respins
21,1.0,capalna i. sonia,SALAJ,SCOALA GIMNAZIALA FODORA,9.80,9.64,9.96,9.02,9.90,geografie,...,9.70,NaN,9.70,Geografie,9.65,NaN,9.65,Mediu,9.15,Reușit
22,8.0,neag l. adina-maria,CLUJ,"SCOALA CU CLASELE I-VIII ""ION CREANGA"" CLUJ-NA...",9.34,9.19,9.49,9.40,8.75,Istorie,...,7.90,NaN,7.90,Geografie,9.50,NaN,9.50,Experimentat,8.80,Reușit
23,12.0,nes a. anca,CLUJ,SCOALA CU CLASELE I-VIII RASCA,9.27,8.78,9.76,7.20,9.15,Geografie,...,8.00,NaN,8.00,Geografie,8.95,NaN,8.95,Experimentat,8.18,Reușit
24,15.0,matis m. raluca-madalina,CLUJ,GRUP SCOLAR HUEDIN,9.18,8.57,9.80,9.17,6.55,Geografie,...,8.10,NaN,8.10,Geografie,9.30,NaN,9.30,Experimentat,8.80,Reușit
25,16.0,sztoica f. denisa-andrada,CLUJ,"SCOALA CU CLASELE I-VIII ""ION AGARBICEANU"" CLU...",9.16,8.90,9.42,8.62,9.35,Istorie,...,6.60,NaN,6.60,Geografie,8.25,NaN,8.25,Experimentat,8.02,Reușit
26,18.0,muresan c. paula-corina,CLUJ,"SCOALA CU CLASELE I-VIII ""IULIU HATIEGANU"" CLU...",9.12,8.69,9.55,7.25,8.92,Geografie,...,9.20,NaN,9.20,Geografie,9.35,NaN,9.35,Experimentat,8.47,Reușit
27,22.0,duca f. sharon,CLUJ,"SCOALA CU CLASELE I-VIII ""NICOLAE IORGA"" CLUJ-...",9.07,8.47,9.68,8.30,7.60,Geografie,...,8.75,NaN,8.75,Geografie,9.70,NaN,9.70,Avansat,9.25,Reușit
28,28.0,botca i. codruta-maria,CLUJ,SCOALA CU CLASELE I-VIII NR. 9 CLUJ-NAPOCA,8.99,8.22,9.76,8.42,7.75,Geografie,...,7.70,NaN,7.70,Logica si argumentare,8.60,NaN,8.60,Avansat,8.20,Reușit
29,1.0,popa v. ana maria,CLUJ,SCOALA CU CLASELE I-VIII BAISOARA,6.71,5.69,7.73,5.80,6.00,Geografie,...,1.10,NaN,1.10,"Anatomie si fiziologie umana, genetica si ecol...",8.50,NaN,8.50,Experimentat,5.20,Respins
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,1.0,vomir m. marian,CLUJ,"SCOALA CU CLASELE I-VIII ""TEODOR MURASANU"" TURDA",10.00,10.00,10.00,10.00,10.00,Istorie,...,9.80,NaN,9.80,Informatica T1 C/C++,8.85,8.5,8.85,Experimentat,9.35,Reușit
157,2.0,zahan d. raul dumitru,CLUJ,"SCOALA CU CLASELE I-VIII ""AVRAM IANCU"" TURDA",9.92,9.85,10.00,9.55,10.00,Geografie,...,8.85,NaN,8.85,Informatica T1 C/C++,8.70,NaN,8.70,Experimentat,8.33,Reușit
158,3.0,tritean a. alexandra,CLUJ,"SCOALA CU CLASELE I-VIII ""AVRAM IANCU"" TURDA",9.78,9.58,9.99,9.30,9.70,Geografie,...,9.45,NaN,9.45,Informatica T1 C/C++,7.50,NaN,7.50,Experimentat,8.53,Reușit
159,4.0,giurgiu t. calin,CLUJ,"SCOALA CU CLASELE I-VIII ""TEODOR MURASANU"" TURDA",9.76,9.82,9.71,9.80,10.00,Geografie,...,9.45,NaN,9.45,Informatica T1 C/C++,8.20,7.8,8.20,Experimentat,8.55,Reușit
160,5.0,nistor d. dorian-traian,CLUJ,"SCOALA CU CLASELE I-VIII ""ANDREI SAGUNA"" TURDA",9.61,9.30,9.92,8.40,9.50,Geografie,...,8.65,NaN,8.65,Informatica T1 C/C++,9.05,8.6,9.05,Experimentat,8.07,Reușit
161,8.0,palacean e. gelu-ionut,CLUJ,"SCOALA CU CLASELE I-VIII ""ANDREI SAGUNA"" TURDA",9.41,8.90,9.92,7.55,9.17,Geografie,...,8.05,8.05,8.05,Informatica T1 C/C++,6.10,6.0,6.10,Experimentat,7.92,Reușit
162,9.0,stefan z. norbert,CLUJ,"SCOALA CU CLASELE I-VIII ""TEODOR MURASANU"" TURDA",9.31,8.91,9.71,7.87,9.27,Geografie,...,9.75,NaN,9.75,Informatica T1 C/C++,9.65,NaN,9.65,Experimentat,9.10,Reușit
163,11.0,lacan t. maria-adriana,CLUJ,"COLEGIUL NATIONAL ""MIHAI VITEAZUL"" TURDA",9.25,8.90,9.61,7.92,9.35,Geografie,...,8.35,NaN,8.35,Informatica T1 C/C++,7.40,NaN,7.40,Experimentat,8.28,Reușit
164,14.0,mocan t. suzana-iuliana,CLUJ,"SCOALA CU CLASELE I-VIII ""ANDREI SAGUNA"" TURDA",9.14,8.64,9.64,8.15,8.20,Geografie,...,5.05,NaN,5.05,"Anatomie si fiziologie umana, genetica si ecol...",6.45,6.3,6.45,Avansat,6.12,Reușit
165,17.0,coroian i. ligia,CLUJ,SCOALA CU CLASELE I-VIII CALARASI,8.96,8.19,9.74,6.97,8.70,Geografie,...,8.90,NaN,8.90,Geografie,7.90,NaN,7.90,Avansat,7.65,Reușit
166,19.0,giurgiu a. alina,ALBA,SCOALA CU CLASELE I-VIII OCOLIS,8.67,7.67,9.68,6.62,7.47,geografie,...,6.50,NaN,6.50,"Anatomie si fiziologie umana, genetica si ecol...",8.10,NaN,8.10,Mediu,6.53,Reușit
167,28.0,pataki a. vlad,CLUJ,"SCOALA CU CLASELE I-VIII ""AVRAM IANCU"" TURDA",7.13,6.10,8.17,4.02,6.35,Istorie,...,5.70,NaN,5.70,Biologie vegetala si animala T1,6.75,NaN,6.75,Avansat,5.85,Respins
168,2.0,nagy e. maria,CLUJ,"SCOALA CU CLASELE I-VIII ""IOAN OPRIS"" TURDA",9.81,9.70,9.93,9.35,9.77,Istorie,...,8.90,NaN,8.90,"Anatomie si fiziologie umana, genetica si ecol...",9.90,NaN,9.90,Experimentat,9.07,Reușit
169,6.0,pop f. ioana,CLUJ,"SCOALA CU CLASELE I-VIII ""IOAN OPRIS"" TURDA",9.67,9.39,9.95,8.95,9.42,Istorie,...,9.15,NaN,9.15,Chimie organica T1 Nivel II,9.00,NaN,9.00,Experimentat,8.90,Reușit
170,11.0,dumitru i. lavinia,CLUJ,"SCOALA CU CLASELE I-VIII ""IOAN OPRIS"" TURDA",9.64,9.45,9.84,9.10,9.30,Geografie,...,8.70,NaN,8.70,Chimie anorganica T2 Nivel II,9.90,NaN,9.90,Experimentat,9.45,Reușit
171,12.0,muresan v. adela-ramona,CLUJ,"SCOALA CU CLASELE I-VIII ""ANDREI SAGUNA"" TURDA",9.61,9.28,9.94,8.75,9.10,Geografie,...,8.20,NaN,8.20,"Anatomie si fiziologie umana, genetica si ecol...",9.60,NaN,9.60,Experimentat,8.88,Reușit
172,17.0,bogdan c. horia-andrei,CLUJ,"SCOALA CU CLASELE I-VIII ""TEODOR MURASANU"" TURDA",9.50,9.33,9.68,8.35,9.65,Geografie,...,8.65,NaN,8.65,Chimie organica T1 Nivel II,8.80,NaN,8.80,Experimentat,7.72,Reușit
173,18.0,rus v. liliana,CLUJ,"SCOALA CU CLASELE I-VIII ""ANDREI SAGUNA"" TURDA",9.48,9.14,9.82,8.82,8.60,Geografie,...,7.60,NaN,7.60,"Anatomie si fiziologie umana, genetica si ecol...",9.00,NaN,9.00,Experimentat,7.53,Reușit
174,19.0,calugar v. ana-maria,CLUJ,"SCOALA CU CLASELE I-VIII ""ANDREI SAGUNA"" TURDA",9.47,9.07,9.87,8.75,8.52,Geografie,...,8.15,NaN,8.15,"Anatomie si fiziologie umana, genetica si ecol...",9.60,NaN,9.60,Experimentat,8.32,Reușit
175,24.0,persa f. roxana maria,CLUJ,"SCOALA CU CLASELE I-VIII ""GEORGE BARITIU"" TURDA",9.34,8.93,9.75,8.50,9.42,Geografie,...,7.30,NaN,7.30,"Anatomie si fiziologie umana, genetica si ecol...",9.15,NaN,9.15,Experimentat,6.65,Respins
176,26.0,todea d. daniel,CLUJ,"SCOALA CU CLASELE I-VIII ""IOAN OPRIS"" TURDA",9.30,8.86,9.74,9.15,8.02,Istorie,...,8.50,NaN,8.50,"Anatomie si fiziologie umana, genetica si ecol...",9.40,NaN,9.40,Experimentat,8.63,Reușit
177,1.0,agratini o. ada,CLUJ,SCOALA ELF,9.72,9.56,9.89,9.45,9.25,Istorie,...,9.80,NaN,9.80,Sociologie,9.10,NaN,9.10,Experimentat,9.47,Reușit
178,2.0,crisan a. radu-cristian,CLUJ,"COLEGIUL NATIONAL ""MIHAI VITEAZUL"" TURDA",9.68,9.50,9.87,9.10,9.40,Istorie,...,10.00,NaN,10.00,Sociologie,10.00,NaN,10.00,Experimentat,9.33,Reușit
179,4.0,trofin i. vlad-ioan,CLUJ,"SCOALA CU CLASELE I-VIII ""ANDREI SAGUNA"" TURDA",9.51,9.20,9.83,8.02,9.60,Geografie,...,9.50,NaN,9.50,Sociologie,9.50,NaN,9.50,Avansat,9.20,Reușit
180,7.0,dan p. paula,CLUJ,"COLEGIUL NATIONAL ""MIHAI VITEAZUL"" TURDA",9.37,9.19,9.56,9.00,9.07,Istorie,...,10.00,NaN,10.00,Sociologie,9.50,NaN,9.50,Experimentat,9.57,Reușit
181,13.0,oprea v. adriana-gabriela,CLUJ,"SCOALA CU CLASELE I-VIII ""ANDREI SAGUNA"" TURDA",9.14,8.52,9.76,7.12,8.65,Geografie,...,10.00,NaN,10.00,Logica si argumentare,9.80,NaN,9.80,Experimentat,9.55,Reușit
182,17.0,marincean a. daniela-augusta-mihaela,CLUJ,"SCOALA CU CLASELE I-VIII ""ANDREI SAGUNA"" TURDA",9.03,8.26,9.80,7.20,7.60,Geografie,...,10.00,NaN,10.00,Geografie,9.05,NaN,9.05,Experimentat,8.87,Reușit
183,20.0,cernea i. irimie,CLUJ,SCOALA CU CLASELE I-VIII MOLDOVENESTI,8.98,8.29,9.68,8.15,7.82,Istorie,...,9.60,NaN,9.60,Filosofie,9.00,NaN,9.00,Experimentat,7.88,Reușit
184,22.0,pintilie c. laura,CLUJ,"SCOALA CU CLASELE I-VIII ""AVRAM IANCU"" TURDA",8.89,8.55,9.24,8.35,8.50,Geografie,...,6.50,NaN,6.50,Fizica,5.45,NaN,5.45,Incepator,6.35,Reușit
185,24.0,aruncutean d. domnita-stanca,CLUJ,"SCOALA CU CLASELE I-VIII ""ANDREI SAGUNA"" TURDA",8.83,8.16,9.50,8.45,6.55,Geografie,...,10.00,NaN,10.00,Logica si argumentare,10.00,NaN,10.00,Experimentat,9.80,Reușit

In [22]:
s1.keys()

Index([u'Unnamed: 0', u'Nume', u'Unnamed: 2', u'SCOALA', u'Media\nla admitere',
       u'Media\nteze nationale', u'Media de\nabsolvire',
       u'\nNota la\nlimba romana', u'Nota la\nmatematica', u'OPTIONAL8',
       u'OPTIONAL8 NOTA', u'Limba materna8', u'Limba materna8 nota',
       u'Poziția în ierarhie pe județ', u'Poziția în ierarhie pe țară',
       u'Unitatea de învățământ', u'Județul', u'Promotie anterioară',
       u'Forma învățământ', u'Specializare',
       u'Limba și literatura română\r\nCompetențe',
       u'Limba și literatura română\r\nScris',
       u'Limba și literatura română\r\nContestație',
       u'Limba și literatura română\r\nNota finală',
       u'Limba și literatura maternă',
       u'Limba și literatura maternă\r\nCompetențe',
       u'Limba și literatura maternă\r\nScris',
       u'Limba și literatura maternă\r\nContestație',
       u'Limba și literatura maternă\r\nNota finală',
       u'Limba modernă studiată', u'Limba modernă studiată\r\nNota',
       u'Disciplina obligatorie a profilului',
       u'Disciplina obligatorie a profilului\r\nNota',
       u'Disciplina obligatorie a profilului\r\nContestație',
       u'Disciplina obligatorie a profilului\r\nNota finală',
       u'Disciplina la alegere', u'Disciplina la alegere\r\nNota',
       u'Disciplina la alegere\r\nContestație',
       u'Disciplina la alegere\r\nNota finală', u'Competențe digitale',
       u'Media', u'Rezultatul final'],
      dtype='object')

In [23]:
s1['Limba și literatura română\r\nScris']

0      7.10
1      7.75
2      7.60
3      9.50
4      9.00
5      7.10
6      5.00
7      7.35
8      5.00
9      3.05
10     5.80
11     5.10
12     5.00
13     9.00
14     4.20
15     3.90
16     4.45
17     5.00
18     0.00
19     5.00
20     4.10
21     8.10
22     9.00
23     7.60
24     9.00
25     9.20
26     6.85
27     9.30
28     8.30
29     6.00
       ...
156    9.40
157    7.45
158    8.65
159    8.00
160    6.50
161    9.60
162    6.90
163    9.10
164    6.25
165    6.15
166    5.00
167    4.60
168    8.40
169    8.55
170    9.75
171    8.85
172    5.70
173    6.00
174    7.20
175    3.50
176    8.00
177    9.50
178    8.00
179    8.60
180    9.20
181    8.85
182    7.55
183    5.05
184    7.10
185    9.40
Name: Limba și literatura română\r\nScris, Length: 186, dtype: float64

In [34]:
s1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 186 entries, 0 to 185
Data columns (total 42 columns):
Unnamed: 0                                          179 non-null float64
Nume                                                186 non-null object
Unnamed: 2                                          186 non-null object
SCOALA                                              186 non-null object
Media
la admitere                                   186 non-null float64
Media
teze nationale                                186 non-null float64
Media de
absolvire                                  186 non-null float64

Nota la
limba romana                               186 non-null float64
Nota la
matematica                                  186 non-null float64
OPTIONAL8                                           186 non-null object
OPTIONAL8 NOTA                                      186 non-null float64
Limba materna8                                      186 non-null object
Limba materna8 nota                                 186 non-null object
Poziția în ierarhie pe județ                        186 non-null int64
Poziția în ierarhie pe țară                         186 non-null int64
Unitatea de învățământ                              186 non-null object
Județul                                             186 non-null object
Promotie anterioară                                 186 non-null object
Forma învățământ                                    186 non-null object
Specializare                                        186 non-null object
Limba și literatura română
Competențe              185 non-null object
Limba și literatura română
Scris                   186 non-null float64
Limba și literatura română
Contestație             39 non-null float64
Limba și literatura română
Nota finală             186 non-null float64
Limba și literatura maternă                         17 non-null object
Limba și literatura maternă
Competențe             17 non-null object
Limba și literatura maternă
Scris                  17 non-null float64
Limba și literatura maternă
Contestație            3 non-null float64
Limba și literatura maternă
Nota finală            17 non-null float64
Limba modernă studiată                              186 non-null object
Limba modernă studiată
Nota                        134 non-null object
Disciplina obligatorie a profilului                 186 non-null object
Disciplina obligatorie a profilului
Nota           186 non-null float64
Disciplina obligatorie a profilului
Contestație    18 non-null float64
Disciplina obligatorie a profilului
Nota finală    186 non-null float64
Disciplina la alegere                               186 non-null object
Disciplina la alegere
Nota                         186 non-null float64
Disciplina la alegere
Contestație                  23 non-null float64
Disciplina la alegere
Nota finală                  186 non-null float64
Competențe digitale                                 185 non-null object
Media                                               186 non-null float64
Rezultatul final                                    186 non-null object
dtypes: float64(20), int64(2), object(20)
memory usage: 48.0+ KB

In [38]:
dat = s1[['Media de\nabsolvire','Nota la\nmatematica','\nNota la\nlimba romana','Unitatea de învățământ', 'Limba și literatura română\r\nScris']]

In [39]:
dat.shape

(186, 5)

In [40]:
dat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 186 entries, 0 to 185
Data columns (total 5 columns):
Media de
absolvire                   186 non-null float64
Nota la
matematica                   186 non-null float64

Nota la
limba romana                186 non-null float64
Unitatea de învățământ               186 non-null object
Limba și literatura română
Scris    186 non-null float64
dtypes: float64(4), object(1)
memory usage: 8.0+ KB

In [41]:
dat.head()

,Media de absolvire,Nota la matematica,Nota la limba romana,Unitatea de învățământ,Limba și literatura română Scris
0,9.97,10.00,7.85,"Liceul Teoretic ""Bathory Istvan"" Cluj-Napoca",7.10
1,9.69,9.55,7.90,"Liceul Teoretic ""Bathory Istvan"" Cluj-Napoca",7.75
2,9.69,9.55,7.90,"Liceul Teoretic ""Marton Aron"" Miercurea Ciuc",7.60
3,9.70,9.57,8.35,"Liceul Teoretic ""Bathory Istvan"" Cluj-Napoca",9.50
4,9.58,8.95,7.37,"Liceul Teoretic ""Bathory Istvan"" Cluj-Napoca",9.00

In [53]:
dat['Unitatea de învățământ']

0      Liceul Teoretic "Bathory Istvan" Cluj-Napoca
1      Liceul Teoretic "Bathory Istvan" Cluj-Napoca
2      Liceul Teoretic "Marton Aron" Miercurea Ciuc
3      Liceul Teoretic "Bathory Istvan" Cluj-Napoca
4      Liceul Teoretic "Bathory Istvan" Cluj-Napoca
5      Liceul Teoretic "Bathory Istvan" Cluj-Napoca
6      Liceul Teoretic "Bathory Istvan" Cluj-Napoca
7                    Colegiul "Emil Negrutiu" Turda
8                    Colegiul "Emil Negrutiu" Turda
9                    Colegiul "Emil Negrutiu" Turda
10                   Colegiul "Emil Negrutiu" Turda
11                            Colegiul Tehnic Turda
12                   Colegiul "Emil Negrutiu" Turda
13                   Colegiul "Emil Negrutiu" Turda
14                   Colegiul "Emil Negrutiu" Turda
15                   Colegiul "Emil Negrutiu" Turda
16                   Colegiul "Emil Negrutiu" Turda
17                   Colegiul "Emil Negrutiu" Turda
18           Colegiul Tehnic "Dr. Ioan Ratiu" Turda
19                            Colegiul Tehnic Turda
20                   Colegiul "Emil Negrutiu" Turda
21       Colegiul Economic "Iulian Pop" Cluj-Napoca
22       Colegiul Economic "Iulian Pop" Cluj-Napoca
23       Colegiul Economic "Iulian Pop" Cluj-Napoca
24       Colegiul Economic "Iulian Pop" Cluj-Napoca
25       Colegiul Economic "Iulian Pop" Cluj-Napoca
26       Colegiul Economic "Iulian Pop" Cluj-Napoca
27       Colegiul Economic "Iulian Pop" Cluj-Napoca
28       Colegiul Economic "Iulian Pop" Cluj-Napoca
29          Colegiul National "Ionita Asan" Caracal
                           ...
156        Colegiul National "Mihai Viteazul" Turda
157          Liceul Teoretic "Liviu Rebreanu" Turda
158        Colegiul National "Mihai Viteazul" Turda
159        Colegiul National "Mihai Viteazul" Turda
160        Colegiul National "Mihai Viteazul" Turda
161        Colegiul National "Mihai Viteazul" Turda
162        Colegiul National "Mihai Viteazul" Turda
163        Colegiul National "Mihai Viteazul" Turda
164        Colegiul National "Mihai Viteazul" Turda
165        Colegiul National "Mihai Viteazul" Turda
166        Colegiul National "Mihai Viteazul" Turda
167                           Colegiul Tehnic Turda
168        Colegiul National "Mihai Viteazul" Turda
169        Colegiul National "Mihai Viteazul" Turda
170        Colegiul National "Mihai Viteazul" Turda
171        Colegiul National "Mihai Viteazul" Turda
172        Colegiul National "Mihai Viteazul" Turda
173        Colegiul National "Mihai Viteazul" Turda
174        Colegiul National "Mihai Viteazul" Turda
175        Colegiul National "Mihai Viteazul" Turda
176        Colegiul National "Mihai Viteazul" Turda
177        Colegiul National "Mihai Viteazul" Turda
178        Colegiul National "Mihai Viteazul" Turda
179        Colegiul National "Mihai Viteazul" Turda
180        Colegiul National "Mihai Viteazul" Turda
181        Colegiul National "Mihai Viteazul" Turda
182        Colegiul National "Mihai Viteazul" Turda
183        Colegiul National "Mihai Viteazul" Turda
184                           Colegiul Tehnic Turda
185        Colegiul National "Mihai Viteazul" Turda
Name: Unitatea de învățământ, Length: 186, dtype: object

In [56]:
le = LabelEncoder()
dat['Unitatea de învățământ'] = le.fit_transform(dat['Unitatea de învățământ'])

c:\python27\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [57]:
dat['Unitatea de învățământ']

0      16
1      16
2      18
3      16
4      16
5      16
6      16
7       0
8       0
9       0
10      0
11      9
12      0
13      0
14      0
15      0
16      0
17      0
18      8
19      9
20      0
21      1
22      1
23      1
24      1
25      1
26      1
27      1
28      1
29      6
       ..
156     7
157    17
158     7
159     7
160     7
161     7
162     7
163     7
164     7
165     7
166     7
167     9
168     7
169     7
170     7
171     7
172     7
173     7
174     7
175     7
176     7
177     7
178     7
179     7
180     7
181     7
182     7
183     7
184     9
185     7
Name: Unitatea de învățământ, Length: 186, dtype: int32

In [59]:
X = dat.loc[:, dat.columns != 'Limba și literatura română\r\nScris']

In [60]:
X.shape

(186, 4)

In [61]:
y = s1['Limba și literatura română\r\nScris'].values.reshape(-1,1)

In [62]:
y

array([[ 7.1 ],
       [ 7.75],
       [ 7.6 ],
       [ 9.5 ],
       [ 9.  ],
       [ 7.1 ],
       [ 5.  ],
       [ 7.35],
       [ 5.  ],
       [ 3.05],
       [ 5.8 ],
       [ 5.1 ],
       [ 5.  ],
       [ 9.  ],
       [ 4.2 ],
       [ 3.9 ],
       [ 4.45],
       [ 5.  ],
       [ 0.  ],
       [ 5.  ],
       [ 4.1 ],
       [ 8.1 ],
       [ 9.  ],
       [ 7.6 ],
       [ 9.  ],
       [ 9.2 ],
       [ 6.85],
       [ 9.3 ],
       [ 8.3 ],
       [ 6.  ],
       [ 7.15],
       [ 9.05],
       [ 8.05],
       [ 5.4 ],
       [ 7.05],
       [ 9.2 ],
       [ 9.05],
       [ 7.3 ],
       [ 8.25],
       [ 5.  ],
       [ 7.3 ],
       [ 8.65],
       [ 9.35],
       [ 9.1 ],
       [ 8.25],
       [ 5.25],
       [ 8.4 ],
       [ 6.8 ],
       [ 8.6 ],
       [ 7.85],
       [ 6.8 ],
       [ 2.6 ],
       [ 3.3 ],
       [ 5.8 ],
       [ 5.  ],
       [ 5.  ],
       [ 4.05],
       [ 5.  ],
       [ 3.25],
       [ 5.2 ],
       [ 5.  ],
       [ 3.2 ],
       [10.  ],
       [10.  ],
       [ 9.  ],
       [ 9.  ],
       [ 9.4 ],
       [ 9.6 ],
       [ 9.05],
       [ 9.05],
       [ 7.65],
       [10.  ],
       [ 9.1 ],
       [ 8.15],
       [ 9.  ],
       [ 9.3 ],
       [ 8.7 ],
       [ 7.8 ],
       [ 8.7 ],
       [ 9.2 ],
       [ 9.1 ],
       [ 9.4 ],
       [ 7.25],
       [ 8.8 ],
       [ 8.  ],
       [ 8.95],
       [ 9.4 ],
       [ 9.3 ],
       [ 9.1 ],
       [ 7.2 ],
       [ 9.55],
       [ 9.3 ],
       [ 8.4 ],
       [ 9.3 ],
       [ 7.2 ],
       [ 9.35],
       [ 8.  ],
       [ 8.75],
       [ 8.75],
       [ 8.1 ],
       [ 9.55],
       [ 8.25],
       [ 8.1 ],
       [ 8.55],
       [ 8.6 ],
       [ 6.55],
       [ 7.9 ],
       [ 7.55],
       [ 9.5 ],
       [ 8.1 ],
       [ 8.1 ],
       [ 9.  ],
       [ 9.25],
       [ 9.3 ],
       [ 9.05],
       [ 8.65],
       [ 8.35],
       [10.  ],
       [ 7.05],
       [ 9.35],
       [ 8.9 ],
       [ 8.4 ],
       [ 7.1 ],
       [ 7.5 ],
       [ 6.6 ],
       [ 8.1 ],
       [ 7.75],
       [ 5.85],
       [ 5.35],
       [ 9.35],
       [ 9.2 ],
       [ 9.05],
       [ 6.85],
       [ 8.45],
       [ 8.2 ],
       [ 7.05],
       [ 6.55],
       [ 8.5 ],
       [ 7.5 ],
       [ 6.9 ],
       [ 8.25],
       [ 7.5 ],
       [ 9.1 ],
       [ 8.4 ],
       [ 8.85],
       [ 9.2 ],
       [ 8.4 ],
       [ 6.9 ],
       [ 8.4 ],
       [ 9.2 ],
       [ 9.6 ],
       [ 6.25],
       [ 6.8 ],
       [ 8.  ],
       [ 9.  ],
       [ 3.3 ],
       [ 9.4 ],
       [ 7.45],
       [ 8.65],
       [ 8.  ],
       [ 6.5 ],
       [ 9.6 ],
       [ 6.9 ],
       [ 9.1 ],
       [ 6.25],
       [ 6.15],
       [ 5.  ],
       [ 4.6 ],
       [ 8.4 ],
       [ 8.55],
       [ 9.75],
       [ 8.85],
       [ 5.7 ],
       [ 6.  ],
       [ 7.2 ],
       [ 3.5 ],
       [ 8.  ],
       [ 9.5 ],
       [ 8.  ],
       [ 8.6 ],
       [ 9.2 ],
       [ 8.85],
       [ 7.55],
       [ 5.05],
       [ 7.1 ],
       [ 9.4 ]])

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [66]:
regressor = LinearRegression()  
regressor.fit(X_train, y_train) #training the algorithm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [67]:
#To retrieve the intercept:
print(regressor.intercept_)

#For retrieving the slope:
print(regressor.coef_)

[-2.88065502]
[[ 0.39412107  0.00147129  0.83318523 -0.00265862]]

In [68]:
y_pred = regressor.predict(X_test)

In [69]:
res = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})

In [70]:
res

    Actual  Predicted
0     7.90   7.045981
1     5.25   8.612211
2     8.65   8.800898
3    10.00   9.190849
4     7.05   8.312574
5     9.40   9.040728
6     0.00   4.974162
7     8.10   8.764696
8     7.50   7.608855
9     7.35   6.232516
10    7.10   5.891745
11    6.90   7.498457
12    8.00   6.974486
13    8.00   8.574918
14    7.05   8.385873
15    8.75   8.018514
16    7.30   7.732418
17    9.30   7.530942
18    8.20   7.821090
19    7.75   6.477074
20    5.00   6.158057
21    8.80   8.341531
22    4.05   5.511393
23    9.20   7.185470
24    4.60   3.674134
25    9.10   7.500822
26    9.00   8.828491
27    9.00   8.383964
28    8.85   8.322058
29    5.40   8.607608
30    9.00   7.006230
31    8.40   8.152957
32    8.40   8.819013
33    3.20   4.240195
34    8.25   8.190297
35    6.85   6.934259
36    9.40   7.894937
37    6.55   8.400020

In [73]:
print('Mean Squared Error:', mean_squared_error(y_test, y_pred))

('Mean Squared Error:', 2.2265262351151835)

In [80]:
accuracy_score('Limba și literatura română\r\nScris', y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [36, 38]