In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('note.csv')

In [3]:
df.keys()

Index([u'Unnamed: 0', u'nume', u'judet', u'scoala', u'media la admitere',
       u'media teze nationale', u'media de absolvire',
       u' nota la limba romana', u'nota la matematica', u'optional8',
       u'optional8 nota', u'limba materna8', u'limba materna8 nota ',
       u'Unnamed: 13', u'pozitia in ierarhie pe judet',
       u'pozitia in ierarhie pe tara', u'unitatea de invatamant', u'judetul',
       u'promotie anterioara', u'forma invatamant', u'specializare',
       u'romana oral', u'romana nota', u'romana contestatie', u'romana final',
       u'limba materna', u'materna oral', u'materna nota',
       u'materna contestatie', u'materna final', u'limba moderna',
       u'limba moderna nota', u'disciplina profil', u'disciplina profil nota',
       u'disciplina profil contestatie', u'disciplina profil final',
       u'optional', u'optional nota', u'optional contestatie',
       u'optional final', u'competente digitale', u'media',
       u'rezultatul final'],
      dtype='object')

In [4]:
df.shape

(3116, 43)

In [5]:
df.head()

,Unnamed: 0,nume,judet,scoala,media la admitere,media teze nationale,media de absolvire,nota la limba romana,nota la matematica,optional8,...,disciplina profil nota,disciplina profil contestatie,disciplina profil final,optional,optional nota,optional contestatie,optional final,competente digitale,media,rezultatul final
0,1,cireap p. florin,BIHOR,SC.CU CLS.I-VIII PIETROASA,9.32,9.10,9.54,8.17,9.45,Geografie,...,3.30,NaN,3.30,"Anatomie si fiziologie umana, genetica si ecol...",6.60,NaN,6.60,Avansat,5.07,Respins
1,2,gabor i. ionut darius,BIHOR,"SC.CU CLS.I-VIII ""N.POPOVICIU"" BEIUS",9.12,8.63,9.62,8.30,8.00,Geografie,...,1.55,NaN,1.55,"Anatomie si fiziologie umana, genetica si ecol...",7.55,NaN,7.55,Mediu,5.60,Respins
2,3,bogan s. sebastian doru,BIHOR,SC.CU CLS.I-VIII CALUGARI,8.71,7.90,9.52,7.62,6.97,Geografie,...,2.80,2.3,2.30,"Anatomie si fiziologie umana, genetica si ecol...",6.70,NaN,6.70,Mediu,5.40,Respins
3,4,apati m. mihai bogdan,BIHOR,SC.CU CLS.I-VIII CARASAU,8.36,8.21,8.51,7.30,7.95,Geografie,...,3.85,4.2,3.85,"Anatomie si fiziologie umana, genetica si ecol...",6.30,NaN,6.30,Mediu,5.05,Respins
4,5,filip g. flaviu georgian,BIHOR,"LICEUL PEDAGOGIC ""N.BOLCAS"" BEIUS",8.31,7.73,8.89,6.40,8.72,Istorie,...,3.65,3.4,3.65,"Anatomie si fiziologie umana, genetica si ecol...",8.60,NaN,8.60,Avansat,6.40,Respins

In [6]:
df['romana final']

0       5.30
1       7.70
2       7.20
3       5.00
4       6.95
5       3.80
6       5.00
7       6.20
8       7.10
9       6.60
10      5.00
11      5.70
12      3.95
13      7.50
14      5.00
15      5.00
16      6.20
17      5.10
18      2.40
19      6.00
20      5.00
21      3.25
22      5.00
23      3.80
24      6.50
25      7.75
26      6.45
27      7.50
28      5.00
29      3.80
        ...
3086    5.00
3087    5.20
3088    6.10
3089    5.85
3090    5.10
3091    5.05
3092    3.65
3093    2.20
3094    3.40
3095    3.40
3096    2.80
3097    5.00
3098    5.45
3099    2.80
3100    3.90
3101    5.45
3102    2.25
3103    3.90
3104    5.00
3105    5.50
3106    7.25
3107    6.35
3108    9.10
3109    7.60
3110    8.20
3111    5.10
3112    4.05
3113    5.10
3114    5.00
3115    1.65
Name: romana final, Length: 3116, dtype: float64

In [7]:
df[' nota la limba romana']

0       8.17
1       8.30
2       7.62
3       7.30
4       6.40
5       5.35
6       5.05
7       6.50
8       7.20
9       7.70
10      6.55
11      5.05
12      7.07
13      4.50
14      5.85
15      6.55
16      6.00
17      5.42
18      6.40
19      5.55
20      5.52
21      6.35
22      6.05
23      4.80
24      6.60
25      6.72
26      7.90
27      7.50
28      5.90
29      6.17
        ...
3086    6.25
3087    6.12
3088    8.25
3089    4.55
3090    4.90
3091    4.07
3092    5.60
3093    4.87
3094    3.30
3095    3.92
3096    2.90
3097    4.22
3098    4.52
3099    3.22
3100    4.25
3101    3.65
3102    3.17
3103    6.05
3104    6.25
3105    5.32
3106    5.52
3107    5.52
3108    4.30
3109    5.60
3110    4.50
3111    5.02
3112    4.87
3113    4.85
3114    3.40
3115    3.60
Name:  nota la limba romana, Length: 3116, dtype: float64

In [36]:
avg = df[' nota la limba romana'].mean()
df[' nota la limba romana'] = avg
df[' nota la limba romana']

0                        6.941845
1                        6.941845
2                        6.941845
3                        6.941845
4                        6.941845
5                        6.941845
6                        6.941845
7                        6.941845
8                        6.941845
9                        6.941845
10                       6.941845
11                       6.941845
12                       6.941845
13                       6.941845
14                       6.941845
15                       6.941845
16                       6.941845
17                       6.941845
18                       6.941845
19                       6.941845
20                       6.941845
21                       6.941845
22                       6.941845
23                       6.941845
24                       6.941845
25                       6.941845
26                       6.941845
27                       6.941845
28                       6.941845
29                       6.941845
                           ...
3087                     6.941845
3088                     6.941845
3089                     6.941845
3090                     6.941845
3091                     6.941845
3092                     6.941845
3093                     6.941845
3094                     6.941845
3095                     6.941845
3096                     6.941845
3097                     6.941845
3098                     6.941845
3099                     6.941845
3100                     6.941845
3101                     6.941845
3102                     6.941845
3103                     6.941845
3104                     6.941845
3105                     6.941845
3106                     6.941845
3107                     6.941845
3108                     6.941845
3109                     6.941845
3110                     6.941845
3111                     6.941845
3112                     6.941845
3113                     6.941845
3114                     6.941845
3115                     6.941845
 nota la limba romana    6.941845
Name:  nota la limba romana, Length: 3117, dtype: float64

In [37]:
X = df[' nota la limba romana'].values.reshape(-1,1)  
Y = df['romana final'].values.reshape(-1,1)

In [38]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)

In [39]:
X.mean()

6.941845314505777

In [40]:
Y.mean()

6.659800399523422

In [41]:
regressor = LinearRegression()  
regressor.fit(X_train, Y_train) #training the algorithm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [42]:
Y_pred = regressor.predict(X_test)

In [43]:
print('Mean Squared Error:', mean_squared_error(Y_test, Y_pred))

('Mean Squared Error:', 3.7388141085512134)

In [50]:
mean_absolute_error(Y_test, Y_pred)

1.5869740661652567

In [45]:
regressor.score(X_test, Y_test)

-0.0020392894804364126

In [46]:
res = pd.DataFrame({'Note evaluare':X_test.ravel(), 'Predicted':Y_pred.flatten(), 'Actual': Y_test.flatten()})
res

     Actual  Note evaluare  Predicted
0      7.50       6.941845   6.642338
1      8.50       6.941845   6.642338
2      7.50       6.941845   6.642338
3      8.80       6.941845   6.642338
4      8.30       6.941845   6.642338
5      7.00       6.941845   6.642338
6      5.60       6.941845   6.642338
7      6.50       6.941845   6.642338
8      5.00       6.941845   6.642338
9      6.15       6.941845   6.642338
10     9.00       6.941845   6.642338
11     5.70       6.941845   6.642338
12     8.20       6.941845   6.642338
13     8.60       6.941845   6.642338
14     8.80       6.941845   6.642338
15     8.75       6.941845   6.642338
16     7.70       6.941845   6.642338
17     5.10       6.941845   6.642338
18     9.40       6.941845   6.642338
19     8.80       6.941845   6.642338
20     5.00       6.941845   6.642338
21     6.45       6.941845   6.642338
22     8.70       6.941845   6.642338
23     3.65       6.941845   6.642338
24     6.05       6.941845   6.642338
25     5.35       6.941845   6.642338
26     6.10       6.941845   6.642338
27     8.75       6.941845   6.642338
28     8.90       6.941845   6.642338
29     7.25       6.941845   6.642338
..      ...            ...        ...
594    6.10       6.941845   6.642338
595    6.30       6.941845   6.642338
596    5.00       6.941845   6.642338
597   10.00       6.941845   6.642338
598    7.90       6.941845   6.642338
599    6.20       6.941845   6.642338
600    5.00       6.941845   6.642338
601    5.00       6.941845   6.642338
602    5.80       6.941845   6.642338
603    0.00       6.941845   6.642338
604    9.00       6.941845   6.642338
605    7.60       6.941845   6.642338
606    4.00       6.941845   6.642338
607    8.50       6.941845   6.642338
608    8.80       6.941845   6.642338
609    7.30       6.941845   6.642338
610    5.00       6.941845   6.642338
611    4.20       6.941845   6.642338
612    5.60       6.941845   6.642338
613    6.80       6.941845   6.642338
614    5.20       6.941845   6.642338
615    6.00       6.941845   6.642338
616    6.25       6.941845   6.642338
617    8.10       6.941845   6.642338
618    6.60       6.941845   6.642338
619    8.60       6.941845   6.642338
620    5.90       6.941845   6.642338
621    7.10       6.941845   6.642338
622    7.05       6.941845   6.642338
623    8.70       6.941845   6.642338

[624 rows x 3 columns]

In [47]:
#To retrieve the intercept:
print(regressor.intercept_)

[6.64233768]

In [17]:








#QUESTION










































(res['Predicted']-regressor.intercept_)/res['Note evaluare']

0      0.80999
1      0.80999
2      0.80999
3      0.80999
4      0.80999
5      0.80999
6      0.80999
7      0.80999
8      0.80999
9      0.80999
10     0.80999
11     0.80999
12     0.80999
13     0.80999
14     0.80999
15     0.80999
16     0.80999
17     0.80999
18     0.80999
19     0.80999
20     0.80999
21     0.80999
22     0.80999
23     0.80999
24     0.80999
25     0.80999
26     0.80999
27     0.80999
28     0.80999
29     0.80999
        ...
594    0.80999
595    0.80999
596    0.80999
597    0.80999
598    0.80999
599    0.80999
600    0.80999
601    0.80999
602    0.80999
603    0.80999
604    0.80999
605    0.80999
606    0.80999
607    0.80999
608    0.80999
609    0.80999
610    0.80999
611    0.80999
612    0.80999
613    0.80999
614    0.80999
615    0.80999
616    0.80999
617    0.80999
618    0.80999
619    0.80999
620    0.80999
621    0.80999
622    0.80999
623    0.80999
Length: 624, dtype: float64

In [48]:

print(regressor.coef_)

[[0.]]