In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.options.mode.chained_assignment = None
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [15]:
# in this notebook, we'd like to predict the label 'romana final'
# this is a regression problem, because our label is a continuos value
df = pd.read_csv('note.csv')
df = df.reset_index()


Y = df['rezultatul final']  

X = df[['nume','media teze nationale', 'nota la limba romana','judet8','scoala','media de absolvire','nota la matematica',
       'optional8 nota','limba materna8','promotie anterioara','specializare','limba moderna','disciplina profil','optional']]



def firstname(name):
    fullname_list = name.split(" ")
    return fullname_list[len(fullname_list)-1]

X['nume'] = X['nume'].apply(firstname)


names = X['nume'].str.get_dummies(sep='-').add_prefix('nume_')
names.head()


X = pd.concat([X, names], axis = 1)

#drop the old name column
X = X.drop('nume', axis=1)


number_columns = []
for col in X.columns:
    if X[col].dtype != 'object' and 'nume' not in col:
        number_columns.append(col)
        X[col] = X[col].astype(float)

print number_columns

scaler = StandardScaler()

X_scale = X.copy()
X_scale[number_columns] = scaler.fit_transform(X[number_columns])
X_scale.head()


categorical_features = []
categorical_features_indices = []
for i,c in enumerate(X.columns):
        if X[c].dtype == 'object':
            categorical_features.append(c)
            categorical_features_indices.append(i)      
categorical_features

X_dummy = pd.get_dummies(X_scale, columns=categorical_features)

X_train, X_test, Y_train, Y_test = train_test_split(X_dummy, Y, test_size=0.20, random_state = 40) #same seed to compare results

X_dummy.isna().sum()

['media teze nationale', 'nota la limba romana', 'media de absolvire', 'nota la matematica', 'optional8 nota']

media teze nationale                                                     0
nota la limba romana                                                     0
media de absolvire                                                       0
nota la matematica                                                       0
optional8 nota                                                           0
nume_abel                                                                0
nume_achim                                                               0
nume_ada                                                                 0
nume_adalbert                                                            0
nume_adam                                                                0
nume_adel                                                                0
nume_adela                                                               0
nume_adelin                                                              0
nume_adelina                                                             0
nume_adeline                                                             0
nume_adi                                                                 0
nume_adina                                                               0
nume_adnana                                                              0
nume_adorian                                                             0
nume_adrian                                                              0
nume_adriana                                                             0
nume_adriel                                                              0
nume_adrienn                                                             0
nume_ady                                                                 0
nume_agnes                                                               0
nume_agota                                                               0
nume_agotha                                                              0
nume_aida                                                                0
nume_akos                                                                0
nume_aladin                                                              0
                                                                        ..
specializare_Teologie Penticostala                                       0
specializare_Teologie Reformata                                          0
specializare_Teologie Romano-Catolica                                    0
limba moderna_Engleza                                                    0
limba moderna_Franceza                                                   0
limba moderna_Germana Moderna                                            0
limba moderna_Italiana                                                   0
limba moderna_Japoneza                                                   0
limba moderna_Rusa                                                       0
limba moderna_Spaniola                                                   0
disciplina profil_Istorie                                                0
disciplina profil_Matematica T1                                          0
disciplina profil_Matematica T2                                          0
optional_Anatomie si fiziologie umana, genetica si ecologie umana  T2    0
optional_Biologie vegetala si animala T1                                 0
optional_Chimie anorganica T2 Nivel I                                    0
optional_Chimie anorganica T2 Nivel II                                   0
optional_Chimie organica T1 Nivel I                                      0
optional_Chimie organica T1 Nivel II                                     0
optional_Economie                                                        0
optional_Filosofie                                                       0
optional_Fizica                                                          0
optional_Geografie                                                       0
optional_Informatica T1 C/C++                                            0
optional_Informatica T1 Pascal                                           0
optional_Informatica T2 C/C++                                            0
optional_Informatica T2 Pascal                                           0
optional_Logica si argumentare                                           0
optional_Psihologie                                                      0
optional_Sociologie                                                      0
Length: 3899, dtype: int64

In [16]:
X_dummy.head()

,media teze nationale,nota la limba romana,media de absolvire,nota la matematica,optional8 nota,nume_abel,nume_achim,nume_ada,nume_adalbert,nume_adam,...,optional_Filosofie,optional_Fizica,optional_Geografie,optional_Informatica T1 C/C++,optional_Informatica T1 Pascal,optional_Informatica T2 C/C++,optional_Informatica T2 Pascal,optional_Logica si argumentare,optional_Psihologie,optional_Sociologie
0,0.982249,0.595819,0.643926,1.222560,0.790473,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.581120,0.678269,0.750584,0.184877,0.702863,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,-0.041910,0.246992,0.617262,-0.552236,0.264809,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.222664,0.044039,-0.729293,0.149095,0.527641,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,-0.187000,-0.526769,-0.222669,0.700140,-0.637581,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
from sklearn.decomposition import PCA
#pca = PCA(n_components=2)

#fullDf = pd.concat([X_dummy, df[['rezultatul final']]], axis = 1)

pca = PCA(.7) 
principalComponents = pca.fit_transform(X_dummy)


X_dummy_pca = pca.transform(X_dummy)

# principalDf = pd.DataFrame(data = principalComponents)
# finalDf = pd.concat([principalDf, df[['rezultatul final']]], axis = 1)
# finalDf

In [41]:
X_train, X_test, Y_train, Y_test = train_test_split(X_dummy_pca, Y, test_size=0.20, random_state = 40)
model = RandomForestClassifier(n_jobs=-1, n_estimators=100)
model.fit(X_train, Y_train.ravel())
Y_pred = model.predict(X_test)
print accuracy_score(Y_pred, Y_test)

0.8393475037073653

In [31]:
X_train, X_test, Y_train, Y_test = train_test_split(X_dummy, Y, test_size=0.20, random_state = 40)
model = RandomForestClassifier(n_jobs=-1, n_estimators=100)
model.fit(X_train, Y_train.ravel())
Y_pred = model.predict(X_test)
print accuracy_score(Y_pred, Y_test)

0.8319327731092437

In [47]:
from sklearn.ensemble import GradientBoostingClassifier

X_train, X_test, Y_train, Y_test = train_test_split(X_dummy, Y, test_size=0.20, random_state = 40)
model = GradientBoostingClassifier(n_estimators=100)
model.fit(X_train, Y_train.ravel())
Y_pred = model.predict(X_test)
print accuracy_score(Y_pred, Y_test)

0.8353929807217004

In [49]:
names.head()

,nume_abel,nume_achim,nume_ada,nume_adalbert,nume_adam,nume_adel,nume_adela,nume_adelin,nume_adelina,nume_adeline,...,nume_zina,nume_zita,nume_zoltan,nume_zorand,nume_zsofia,nume_zsolt,nume_zsombor,nume_zsuzsa,nume_zsuzsana,nume_zsuzsanna
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [50]:
allNames = []
for col in names:
    allNames.append(col.replace('nume_', ''))

In [52]:
print len(allNames)
allNames

1023

['abel',
 'achim',
 'ada',
 'adalbert',
 'adam',
 'adel',
 'adela',
 'adelin',
 'adelina',
 'adeline',
 'adi',
 'adina',
 'adnana',
 'adorian',
 'adrian',
 'adriana',
 'adriel',
 'adrienn',
 'ady',
 'agnes',
 'agota',
 'agotha',
 'aida',
 'akos',
 'aladin',
 'alban',
 'albert',
 'alberta',
 'alecsandra',
 'alenka',
 'alessandra',
 'alex',
 'alexa',
 'alexandar',
 'alexandra',
 'alexandrina',
 'alexandru',
 'alfred',
 'alia',
 'alice',
 'alicia',
 'alida',
 'alin',
 'alina',
 'alis',
 'alisa',
 'aliz',
 'alizza',
 'alois',
 'alpar',
 'alteea',
 'amalia',
 'amanda',
 'amina',
 'amira',
 'ana',
 'anamaria',
 'anastasia',
 'anasztazia',
 'anca',
 'ancuta',
 'anda',
 'andelice',
 'andi',
 'andor',
 'andra',
 'andrada',
 'andras',
 'andrea',
 'andreea',
 'andreeas',
 'andrei',
 'andreia',
 'andreina',
 'andy',
 'anelise',
 'anett',
 'anetta',
 'angela',
 'angelica',
 'angelo',
 'anghel',
 'angheluta',
 'angyalka',
 'aniko',
 'anisia',
 'anisoara',
 'anita',
 'anna',
 'annabell',
 'annabella',
 'annamaria',
 'anne',
 'annemarie',
 'antal',
 'anton',
 'antonela',
 'antonia',
 'antonina',
 'antonio',
 'antoniu',
 'anuta',
 'apollonia',
 'arabela',
 'arestita',
 'arina',
 'aristide',
 'armando',
 'armin',
 'arnold',
 'aron',
 'arpad',
 'artur',
 'atena',
 'attila',
 'augusta',
 'augustin',
 'aura',
 'aurel',
 'aurelia',
 'aurelian',
 'aurica',
 'aurora',
 'avram',
 'axente',
 'ayla',
 'ayman',
 'balazs',
 'balint',
 'banica',
 'barbara',
 'barna',
 'bazil',
 'beata',
 'beatrice',
 'beatrix',
 'bela',
 'bened',
 'beniamin',
 'benjamin',
 'bernadett',
 'bernadette',
 'bertalan',
 'berti',
 'betina',
 'bettina',
 'betty',
 'bianca',
 'bianco',
 'bianka',
 'biborka',
 'blanka',
 'bogdan',
 'bogdana',
 'boglarka',
 'borbala',
 'boroka',
 'botond',
 'brigitta',
 'brindusa',
 'calin',
 'camelia',
 'cameluta',
 'candina',
 'carina',
 'carla',
 'carmen',
 'carmina',
 'carol',
 'carola',
 'carolina',
 'casian',
 'casiana',
 'catalin',
 'catalina',
 'cateluta',
 'caterina',
 'catrinel',
 'cecilia',
 'celia',
 'cerasela',
 'cezar',
 'cezara',
 'chena',
 'christa',
 'christina',
 'ciprian',
 'cipriana',
 'clara',
 'claudia',
 'claudita',
 'claudiu',
 'codrin',
 'codrina',
 'codrut',
 'codruta',
 'constanta',
 'constantin',
 'constantina',
 'consuela',
 'cora',
 'corin',
 'corina',
 'cornel',
 'cornelia',
 'corneliu',
 'cosmin',
 'cosmina',
 'costache',
 'costan',
 'costel',
 'costica',
 'costin',
 'costina',
 'costinel',
 'costinela',
 'cozmin',
 'crenguta',
 'crina',
 'crinisor',
 'crinuta',
 'cristi',
 'cristian',
 'cristiana',
 'cristina',
 'cristinel',
 'cristinela',
 'cristofer',
 'crizantina',
 'csaba',
 'csilla',
 'csongor',
 'dacian',
 'daciana',
 'dagmar',
 'daiana',
 'dalia',
 'dalis',
 'dalma',
 'damaris',
 'damian',
 'dan',
 'dana',
 'daniel',
 'daniela',
 'daniil',
 'danusia',
 'danut',
 'danuta',
 'daria',
 'darian',
 'darie',
 'darine',
 'dariu',
 'darius',
 'david',
 'dayana',
 'debora',
 'deian',
 'delenke',
 'delia',
 'delinke',
 'demetriu',
 'denis',
 'denisa',
 'denise',
 'diana',
 'diandra',
 'didina',
 'diego',
 'dimitrie',
 'dina',
 'dinu',
 'doina',
 'doinita',
 'domnica',
 'domnita',
 'dora',
 'dorel',
 'doria',
 'dorian',
 'dorin',
 'dorina',
 'dorinel',
 'dorisz',
 'dorottya',
 'doru',
 'dorz',
 'dragan',
 'dragomir',
 'dragos',
 'dragoslava',
 'dumitra',
 'dumitrel',
 'dumitrita',
 'dumitru',
 'dylara',
 'ecaterina',
 'ede',
 'edgard',
 'edina',
 'edit',
 'eduard',
 'elemer',
 'elena',
 'eleonora',
 'elian',
 'eliana',
 'elias',
 'elin',
 'eliodor',
 'elisa',
 'elisabeta',
 'elisei',
 'eliza',
 'elmira',
 'elod',
 'elvira',
 'elvis',
 'ely',
 'elyda',
 'ema',
 'emanuel',
 'emanuela',
 'emanuiela',
 'emese',
 'emil',
 'emilia',
 'emilian',
 'emiliana',
 'emoke',
 'emona',
 'enache',
 'endre',
 'engin',
 'eniko',
 'eonicia',
 'erdal',
 'ergut',
 'erica',
 'erik',
 'erika',
 'ervin',
 'erzsebet',
 'estera',
 'eszter',
 'etelka',
 'eu',
 'eudochia',
 'eugen',
 'eugenia',
 'eula',
 'eusebiu',
 'eva',
 'evelin',
 'evelina',
 'eveline',
 'evelyn',
 'evelyne',
 'evodia',
 'fabian',
 'fanel',
 'fatih',
 'felicia',
 'felician',
 'felix',
 'ferenc',
 'ferencz',
 'filip',
 'fineas',
 'firuta',
 'fivi',
 'flavia',
 'flaviana',
 'flaviu',
 'flavius',
 'floarea',
 'florea',
 'florena',
 'florentin',
 'florentina',
 'flori',
 'florian',
 'floriana',
 'florica',
 'floridana',
 'florin',
 'florina',
 'florinel',
 'florinela',
 'floris',
 'florita',
 'fraguta',
 'francesca',
 'francisc',
 'franciska',
 'gabi',
 'gabor',
 'gabriel',
 'gabriela',
 'gabriell',
 'gabriella',
 'gafia',
 'garofita',
 'gaspar',
 'gavril',
 'gavrila',
 'geanina',
 'gellert',
 'gelu',
 'george',
 'georgel',
 'georgeta',
 'georgia',
 'georgian',
 'georgiana',
 'georgina',
 'gerald',
 'gergely',
 'gergo',
 'gheorghe',
 'gheorghina',
 'gheorghita',
 'ghiocel',
 'ghiulbin',
 'ghiulfidan',
 'giancarlo',
 'giani',
 'gianina',
 'gica',
 'gilda',
 'gina',
 'giorgi',
 'giorgiana',
 'giulia',
 'giuliana',
 'giuliano',
 'gizella',
 'gloria',
 'gratian',
 'gratiana',
 'gregorian',
 'greta',
 'greti',
 'grigore',
 'gunter',
 'gyongyi',
 'gyongyver',
 'gyoparka',
 'gyorgy',
 'gyula',
 'hajnal',
 'hajnalka',
 'hanellore',
 'helena',
 'helga',
 'henriett',
 'henrietta',
 'hermina',
 'hilda',
 'horatiu',
 'horatius',
 'horia',
 'hristina',
 'huba',
 'hunor',
 'iacob',
 'iancu',
 'iani',
 'iarka',
 'iaroslav',
 'iasmina',
 'iazmin',
 'ibolya',
 'ibrahim',
 'ica',
 'iedida',
 'ifigenia',
 'ignac',
 'ilarie',
 'ildiko',
 'ileana',
 'ilenuta',
 'ilie',
 'ilinca',
 'ilma',
 'ilona',
 'imelda',
 'imola',
 'imre',
 'ines',
 'ingrid',
 'ioachim',
 'ioan',
 'ioana',
 'iolanda',
 'ion',
 'ionatan',
 'ionathan',
 'ionel',
 'ionela',
 'ionelia',
 'ionica',
 'ionita',
 'ionut',
 'iosefina',
 'iosif',
 'iozef',
 'irene',
 'irimie',
 'irina',
 'irinel',
 'iringo',
 'irma',
 'isabela',
 'isabella',
 'isabelle',
 'isaura',
 'isidora',
 'istvan',
 'iulia',
 'iulian',
 'iuliana',
 'iuliu',
 'iura',
 'iustin',
 'iustina',
 'iuxel',
 'ivona',
 'izabela',
 'izabella',
 'izolda',
 'jacint',
 'jacinta',
 'jahel',
 'janet',
 'janina',
 'janos',
 'jasmina',
 'jeno',
 'jiva',
 'johanna',
 'jozsef',
 'judit',
 'judita',
 'judith',
 'julia',
 'junior',
 'kalman',
 'kamil',
 'kamilla',
 'karina',
 'karla',
 'karles',
 'karmen',
 'karola',
 'karoly',
 'kata',
 'katalin',
 'katalina',
 'katinka',
 'kinga',
 'kitty',
 'klara',
 'klaudia',
 'kristian',
 'kristof',
 'kriszta',
 'krisztian',
 'krisztina',
 'lacramioara',
 'lajos',
 'larisa',
 'laszlo',
 'laura',
 'laurean',
 'laurentiu',
 'lavinia',
 'laviniu',
 'lazar',
 'lehel',
 'leila',
 'lelia',
 'lena',
 'lenke',
 'lenuta',
 'leonard',
 'leontin',
 'leontina',
 'letitia',
 'levente',
 'lia',
 'liana',
 'liber',
 'lidia',
 'liedia',
 'ligia',
 'liliana',
 'lilla',
 'lina',
 'linca',
 'linda',
 'lioara',
 'lisa',
 'livia',
 'liviu',
 'lizuca',
 'lorand',
 'lorant',
 'loredana',
 'lorena',
 'lorenzzo',
 'loreta',
 'loriana',
 'lorin',
 'luana',
 'lucia',
 'lucian',
 'luciana',
 'lucica',
 'lucretia',
 'ludovic',
 'ludovica',
 'luigi',
 'luisa',
 'luiza',
 'luki',
 'luminita',
 'luxandra',
 'madalin',
 'madalina',
 'madian',
 'maftei',
 'magda',
 'magdalena',
 'magdolna',
 'malvina',
 'malvinia',
 'manuel',
 'manuela',
 'mara',
 'marc',
 'marcel',
 'marcela',
 'margareta',
 'margit',
 'maria',
 'mariam',
 'marian',
 'mariana',
 'maricel',
 'maricela',
 'maricica',
 'marie',
 'marija',
 'marika',
 'marilena',
 'marin',
 'marina',
 'marinel',
 'marinela',
 'mario',
 'marioara',
 'mariuca',
 'marius',
 'mariuta',
 'mark',
 'marlena',
 'marta',
 'martin',
 'mary',
 'matei',
 'matild',
 'matyas',
 'maximilian',
 'mazin',
 'medina',
 'melania',
 'melek',
 'melinda',
 'melisa',
 'melitta',
 'meloria',
 'memnona',
 'michael',
 'mihaela',
 'mihai',
 'mihail',
 'mihaita',
 'mihnea',
 'miklos',
 'milan',
 'mina',
 'minerva',
 'minodora',
 'mioara',
 'mirabela',
 'mircea',
 'mirel',
 'mirela',
 'miriam',
 'miriana',
 'miron',
 'miruna',
 'mitica',
 'monalisa',
 'monica',
 'monika',
 'mozes',
 'mugurel',
 'nadia',
 'naim',
 'nandor',
 'naomi',
 'narcis',
 'narcisa',
 'narcisz',
 'nastasia',
 'natalia',
 'natanael',
 'neculai',
 'nelica',
 'nelida',
 'nelu',
 'nelutu',
 'neri',
 'nicola',
 'nicolae',
 'nicolai',
 'nicole',
 'nicoleta',
 'nicu',
 'niculina',
 'niculita',
 'nicusor',
 'nikolet',
 'nikoleta',
 'nikolett',
 'nina',
 'nineta',
 'nistor',
 'nixilia',
 'noemi',
 'noemia',
 'nora',
 'norbert',
 'nuta',
 'oana',
 'octav',
 'octavia',
 'octavian',
 'odon',
 'ofelia',
 'olga',
 'olguta',
 'olimpia',
 'olimpiada',
 'olimpiu',
 'olivia',
 'olivian',
 'oliviu',
 'oltita',
 'onda',
 'ondina',
 'onisim',
 'oriana',
 'orlando',
 'orsolya',
 'otilia',
 'otto',
 'ovidia',
 'ovidiu',
 'pal',
 'palaguta',
 'palma',
 'pamela',
 'panorica',
 'parascheva',
 'paraschiva',
 'partene',
 'partenie',
 'patricia',
 'patrik',
 'paul',
 'paula',
 'paulina',
 'pavel',
 'persida',
 'peter',
 'petra',
 'petre',
 'petrea',
 'petria',
 'petrian',
 'petrica',
 'petrina',
 'petrisor',
 'petronel',
 'petronela',
 'petru',
 'petrus',
 'petrut',
 'petruta',
 'piroska',
 'pompilia',
 'pompiliu',
 'predrag',
 'pricop',
 'radian',
 'radu',
 'raducu',
 'rafael',
 'rafaela',
 'rahela',
 'rainer',
 'raisa',
 'raluca',
 'rambo',
 'ramona',
 'raoul',
 'raphaela',
 'rares',
 'raul',
 'raymond',
 'razvan',
 'rebeca',
 'rebeka',
 'reinhard',
 'reka',
 'remus',
 'renata',
 'renate',
 'renatta',
 'renatto',
 'rezso',
 'richard',
 'rita',
 'robert',
 'roberto',
 'rodica',
 'rodin',
 'roland',
 'romelia',
 'romeo',
 'romica',
 'romina',
 'romulus',
 'ronnye',
 'rosa',
 'rosana',
 'roxana',
 'roxane',
 'rozalia',
 'rozeta',
 'ruben',
 'rudolf',
 'rusalina',
 'ruxanda',
 'ruxandra',
 'sabin',
 'sabina',
 'saftica',
 'salomea',
 'salomeea',
 'samuel',
 'sanda',
 'sandor',
 'sandu',
 'sara',
 'sarah',
 'sarolta',
 'scarlett',
 'sebastian',
 'seiran',
 'semida',
 'serban',
 'sergiu',
 'serioja',
 'sevastiana',
 'sever',
 'shandijeh',
 'sharon',
 'silvana',
 'silvia',
 'silviu',
 'simina',
 'simion',
 'simona',
 'sintia',
 'sinziana',
 'sixtine',
 'smaranda',
 'sofia',
 'sofica',
 'solomon',
 'soma',
 'sonia',
 'sorin',
 'sorina',
 'speranta',
 'stanca',
 'stefan',
 'stefana',
 'stefanel',
 'stefania',
 'stefanica',
 'stefanita',
 'stefanut',
 'stelea',
 'stelian',
 'steluta',
 'sunita',
 'susana',
 'suzana',
 'szabina',
 'szabolcs',
 'szende',
 'szidonia',
 'szilamer',
 'szilard',
 'szilveszter',
 'szilvia',
 'tabita',
 'tamara',
 'tamas',
 'tana',
 'tania',
 'tanita',
 'tascu',
 'taselia',
 'tatiana',
 'teia',
 'tekla',
 'teodor',
 'teodora',
 'teofana',
 'teofil',
 'teona',
 'tereza',
 'thabita',
 'thadeus',
 'theodor',
 'theodora',
 'tiberiu',
 'tiberius',
 'tibor',
 'tihamer',
 'timea',
 'timeea',
 'timotei',
 'tincuta',
 'tinut',
 'titus',
 'toader',
 'toma',
 'tradian',
 'traian',
 'tristan',
 'tudor',
 'tudorel',
 'tunde',
 'ungureanu',
 'vadim',
 'vahap',
 'valentin',
 'valentina',
 'valentino',
 'valer',
 'valeria',
 'valerica',
 'valeriu',
 'vali',
 'vanessa',
 'varvara',
 'vaselena',
 'vasile',
 'vasilica',
 'verginica',
 'verona',
 'veronica',
 'veronika',
 'vicentiu',
 'victor',
 'victoria',
 'victorita',
 'viktoria',
 'vilmos',
 'vinicius',
 'violeta',
 'viorel',
 'viorela',
 'viorica',
 'virgil',
 'virginia',
 'virginica',
 'vistian',
 'viviana',
 'vlad',
 'vladimir',
 'vladut',
 ...]

In [53]:
df_names = pd.DataFrame(allNames, columns=['name'])

In [54]:
df_names.head()

       name
0      abel
1     achim
2       ada
3  adalbert
4      adam

In [57]:
df_names.head(400).to_csv("names.csv")

In [64]:
df_names.iloc[401:900].to_csv("names2.csv")

In [65]:
df_names.iloc[901:].to_csv("names3.csv")