In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.options.mode.chained_assignment = None
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [2]:
firstName_gender = pd.read_csv('all_names_gender.csv')
firstName_gender.head()


df = pd.read_csv('note.csv')
df = df.reset_index()

Y = df[['rezultatul final']]  

X = df[['nume','media teze nationale', 'nota la limba romana','judet8','scoala','media de absolvire','nota la matematica',
       'optional8 nota','limba materna8','promotie anterioara','specializare','limba moderna','disciplina profil','optional'
       ,'unitatea de invatamant', 'forma invatamant','judetul']]

def firstname(name):
    fullname_list = name.split(" ")
    return fullname_list[len(fullname_list)-1]

X['nume'] = X['nume'].apply(firstname)


#add gender 
genders = []

for ind, name in enumerate(X['nume']):
    all_first_names = name.split('-')
    male = 0
    female = 0
    
    for first in all_first_names:
        if not firstName_gender[firstName_gender['name'] == first]['ga_gender'].empty:
            gender = firstName_gender[firstName_gender['name'] == first]['ga_gender'].values[0]
            if gender == 'male':
                male +=1
            else:
                female +=1
        
    if male > female:
        genders.append(0)
    else:
        genders.append(1)
        
X['gender'] = genders
#names = X['nume'].str.get_dummies(sep='-').add_prefix('nume_')
#names.head()


#X = pd.concat([X, names], axis = 1)

# #drop the old name column
#X = X.drop('nume', axis=1)

In [3]:
for i,c in enumerate(X.columns):
        if X[c].dtype == 'object':
            lbl = LabelEncoder()
            lbl.fit(list(X[c].values))
            X[c] = lbl.transform(list(X[c].values)) 

for i,c in enumerate(Y.columns):
    if Y[c].dtype == 'object':
        lbl = LabelEncoder()
        lbl.fit(list(Y[c].values))
        Y[c] = lbl.transform(list(Y[c].values)) 
Y.head()
            
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state = 40) #same seed to compare results

            
X.head()

,nume,media teze nationale,nota la limba romana,judet8,scoala,media de absolvire,nota la matematica,optional8 nota,limba materna8,promotie anterioara,specializare,limba moderna,disciplina profil,optional,unitatea de invatamant,forma invatamant,judetul,gender
0,949,9.10,8.17,4,478,9.54,9.45,9.70,0,1,43,0,2,0,252,3,5,0
1,689,8.63,8.30,4,391,9.62,8.00,9.60,0,1,43,0,2,0,252,3,5,0
2,769,7.90,7.62,4,419,9.52,6.97,9.10,0,1,43,0,2,0,252,3,5,0
3,412,8.21,7.30,4,421,8.51,7.95,9.40,0,1,43,0,2,0,252,3,5,0
4,1032,7.73,6.40,4,286,8.89,8.72,8.07,0,1,43,0,2,0,252,3,5,0

In [4]:
from xgboost import XGBClassifier
from vecstack import stacking

ImportError: No module named vecstack